export const ActionTypes = {
    ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
    REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
    FETCH_PRODUCTS_REQUEST: "FETCH_PRODUCTS_REQUEST",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
};